# This is a basic workflow to help you get started with Actions

name: Heroku Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup up NodeJs in frontend-vue
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
          
      - name: Install Dependencies
        run: cd frontend-vue && npm i
          
      - name: Build deployment folder
        run: cd frontend-vue && npm run build
        
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wif3005-sme" #Must be unique in Heroku
          heroku_email: "sonyxs93@gmail.com"
